server:
  port: 8500

spring:
  application:
    name: @project.name@
    version: @project.version@
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/your_schema?serverTimezone=Asia/Shanghai
    username: username
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

swagger:
  enable: true
  title: Lumine Starter
  description: |
    请点击"Authorize"按钮输入token
  host: